# Generated by Django 4.1 on 2022-09-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_property_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='info',
            field=models.TextField(max_length=100),
        ),
    ]
