# Generated by Django 4.1 on 2022-09-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_alter_property_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='info',
            field=models.TextField(),
        ),
    ]
